language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: remainvoter
  password:
    secure: 0cbKDecUJJ/2qO0m7UcAhQeRtxI6EUdpYL5y9Wc8cm3T07LhEs4oA51kJwj3MBgWW5acE63BWcZ1VtbWwMYd/GDsGjDvzzKPev0bG0j3e7nVXwa92RK7bHpVtV85HSnSjvJzf8gjIEdblFzhGbeOS/6+PmrdEydS8/R6NmqT+t7r0HFyGl0fq8bYCbm5OTSeH4CPG5s1zHHICAHMpWggUksQKhjf4W8QngPd2esMBC3i9V6qcQDjjo7NuRktzNNvdNx4gA/FHuT2cpOTRiQtLJAxNsF4aUGTVg+0mZxo84BvV5HISgL8kVTibLlz0MQF/QSGuljlMhS2GKWzWiTlkTfPt0E0vZk/cYM/nEdeGLTyHKSepYCnqsDGf6KzlLPy6DyC5H2bwUC28Z0CedecBtPWSSsLANCjlm4Fxkv3Atcu/pk/aX3vcRaJI/AI9fApMcoEmciYDYD0jAXv4cDhKLhz6/9JDzMZs+yPADwIAJs8L3YCnVnVC7sY9dxiHr/FU1PtOeuPaPtKUwtd2K6m8sCje+4i0ucqfYLLI2H2b6koRNgJ4H3UZ1qtWMyUnfMHYHGIzDCiGwkwyK9LGY53W4hkfHznbE6FJ68FsbonafjhxiSc1XHz+UQ5hdt80J7lmt+3gyzMUuSQtkF2wvfw0z73SCAVjegUoXJM0AIfhc0=
  on:
    tags: true
    repo: remainvoter/eu2019model
    python: 3.6
