language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: DrNickMartin
  password:
    secure: n3fO6oCt7NE6QgXKj9Eda2dYJ1f8e+k+z7/baU/j/DB+lR4SdVl51pi/wZd6AgChqZijutgAjvy8fX0XJJxkzGVdK8voGcqq5fhyvU+dQyt5RHRuuNaLPN8MM0+zczoquPKi/c6LmjMYWxnziQZ3WPpSpFBuOpcrdH/gVQT9DZC/pDgXF8tTsKzLnZRahVyACubdNh51IisKzewkyaHBN5O6qxcvdMZ2X0kifI5QceJIWzZRN77GthTrcq7W9XCGFxQiebKw6ocd/qF9cph626q5m40dM3zZe963AsbEEuYI4BAyE0LHC5GMWZ7rXjxhMcN3jBgIFZ8FfZWd6+AaJO7C3k+C8lP4QmO/l/pE7YiXmeQDQ29c0ZCpf+eiymPZuC7ZuV7V8HGH596hKeCyoYn5tu/9AasxTnmrQ4H4o25q7ZLmZmF5mlqqZ8xk+TpBypAOILV0IMGM9NgvgftMPOkz7MfTvlcJBUTcWQQYLB83gmUJn0VGcOQiLKlQLdC+Dh71GJKxs8KkmYx3a8Z5rkEeigIcU59RvG0enixr8KDLPR7e93KNbuaQf0dHzWkt5LSQniVwBgBApOe8xiVMUG4LHwECkInzm86jfC6FmDGM+1zD/mekyDl19XcqJhLDGr15FixLxcAthu3oag982e7qF9c2Kg5o1X6f0DaINIs=
  on:
    tags: true
    repo: DrNickMartin/eu2019model
    python: 3.6
